database:
  #MySQL database host
  mySQLHost: localhost
  #MySQL connection port number
  mySQLPort: 3306
  #MySQL database name
  mySQLDatabase: PlayerManager
  #MySQL database user
  mySQLUser: root
  #MySQL user's password
  mySQLPassword: ""